from __future__ import annotations

from app.intelligence_sources.catalog import IntelligenceSourceCatalog
from app.intelligence_sources.contracts import (
    DataSensitivity,
    IntelligenceAccessMode as Access,
    IntelligenceCost as Cost,
    IntelligenceDeliveryMode as Delivery,
    IntelligenceSourceCategory as Category,
    IntelligenceSourceDescriptor as Source,
    IntelligenceSourceOrigin as Origin,
    IntelligenceTransport as Transport,
)
from app.intelligence_sources.coverage import (
    RemoteSourceCoverage,
    SourceCoverageEntry,
    SourceImplementationStatus as Status,
)


def _source(
    code: str,
    name: str,
    *,
    categories: set[Category],
    capabilities: set[str],
    transport: Transport = Transport.REST,
    access: Access = Access.NO_AUTH,
    cost: Cost = Cost.FREE,
    origin: Origin = Origin.OTHER,
    countries: set[str] | None = None,
    global_scope: bool = False,
    requires_credentials: bool = False,
    default_enabled: bool = False,
    sensitivity: DataSensitivity = DataSensitivity.PUBLIC,
    documentation_url: str | None = None,
    terms_url: str | None = None,
    notes: str = "",
) -> Source:
    return Source(
        code=code,
        display_name=name,
        categories=frozenset(categories),
        capabilities=frozenset(capabilities),
        transport=transport,
        access_mode=access,
        cost=cost,
        delivery_mode=Delivery.REMOTE_QUERY,
        origin=origin,
        countries=frozenset(countries or set()),
        global_scope=global_scope,
        requires_credentials=requires_credentials,
        default_enabled=default_enabled,
        remote_query_supported=True,
        bulk_download_required=False,
        default_sensitivity=sensitivity,
        raw_secret_storage_allowed=False,
        redistribution_allowed=False,
        documentation_url=documentation_url,
        terms_url=terms_url,
        notes=notes,
    )


# Catalog metadata is deliberately conservative. A descriptor means OSINTXZ
# knows the source/capabilities/access policy; it does NOT claim that a query
# adapter is implemented unless coverage status says ACTIVE/EXISTING_CONNECTOR.
MASSIVE_REMOTE_SOURCES: tuple[Source, ...] = (
    # ---------------- Existing Registry / Breach / Dark Web ----------------
    _source("gleif_lei", "GLEIF LEI API", categories={Category.REGISTRY, Category.FINANCIAL}, capabilities={"lei", "name", "organization"}, origin=Origin.OFFICIAL_API, global_scope=True, default_enabled=True, documentation_url="https://www.gleif.org/en/lei-data/gleif-api"),
    _source("eu_vies", "EU VIES VAT Validation", categories={Category.REGISTRY}, capabilities={"vat_id", "vat_validation"}, origin=Origin.OFFICIAL_API, global_scope=True, default_enabled=True, documentation_url="https://ec.europa.eu/taxation_customs/vies/"),
    _source("opencorporates", "OpenCorporates", categories={Category.REGISTRY}, capabilities={"company_name", "registration_id"}, access=Access.CONTRACT, cost=Cost.MIXED, origin=Origin.AGGREGATOR, global_scope=True, requires_credentials=True, documentation_url="https://api.opencorporates.com/"),
    _source("ua_edr_business", "Ukraine EDR Business", categories={Category.REGISTRY}, capabilities={"company_name", "registration_id", "sole_trader"}, transport=Transport.REMOTE_BACKEND, origin=Origin.OFFICIAL_OPEN_DATA, countries={"UA"}),
    _source("ua_edrsr", "Ukraine EDRSR Court Decisions", categories={Category.REGISTRY}, capabilities={"case_number", "court_decision"}, transport=Transport.REMOTE_BACKEND, origin=Origin.OFFICIAL_OPEN_DATA, countries={"UA"}, sensitivity=DataSensitivity.PUBLIC_SENSITIVE),
    _source("courtlistener", "CourtListener Case Law", categories={Category.REGISTRY}, capabilities={"case_number", "case_name", "court_decision"}, access=Access.FREE_API_KEY, origin=Origin.AGGREGATOR, countries={"US"}, requires_credentials=True, documentation_url="https://www.courtlistener.com/help/api/rest/"),
    _source("courtlistener_recap", "CourtListener RECAP", categories={Category.REGISTRY}, capabilities={"case_number", "federal_docket"}, access=Access.FREE_API_KEY, origin=Origin.AGGREGATOR, countries={"US"}, requires_credentials=True, sensitivity=DataSensitivity.PUBLIC_SENSITIVE, documentation_url="https://www.courtlistener.com/help/api/rest/"),
    _source("uk_companies_house", "UK Companies House", categories={Category.REGISTRY}, capabilities={"company_name", "registration_id"}, access=Access.FREE_API_KEY, origin=Origin.OFFICIAL_API, countries={"GB"}, requires_credentials=True, documentation_url="https://developer.company-information.service.gov.uk/"),
    _source("pl_krs", "Poland KRS", categories={Category.REGISTRY}, capabilities={"registration_id", "company"}, origin=Origin.OFFICIAL_OPEN_DATA, countries={"PL"}, default_enabled=True, documentation_url="https://api-krs.ms.gov.pl/"),
    _source("hibp_breached_account", "Have I Been Pwned — Breached Account", categories={Category.BREACH_INTELLIGENCE}, capabilities={"email", "breach_lookup"}, access=Access.CONTRACT, cost=Cost.MIXED, origin=Origin.BREACH_PROVIDER, global_scope=True, requires_credentials=True, sensitivity=DataSensitivity.BREACH_METADATA, documentation_url="https://haveibeenpwned.com/API/v3"),
    _source("hibp_pwned_passwords", "Have I Been Pwned — Pwned Passwords", categories={Category.BREACH_INTELLIGENCE}, capabilities={"password_exposure"}, origin=Origin.BREACH_PROVIDER, global_scope=True, default_enabled=True, sensitivity=DataSensitivity.BREACH_METADATA, documentation_url="https://haveibeenpwned.com/API/v3"),
    _source("tor_public_onion_fetch", "Tor Public Onion Fetch", categories={Category.DARK_WEB}, capabilities={"onion_url", "email", "domain", "username", "crypto_address", "public_page_observation"}, transport=Transport.TOR_HTTP, origin=Origin.DARKWEB_PUBLICATION, global_scope=True, sensitivity=DataSensitivity.DARKWEB_PUBLIC, documentation_url="https://support.torproject.org/tor-browser/features/onion-services/"),
    _source("tor_onion_discovery", "Tor Public Onion Discovery", categories={Category.DARK_WEB}, capabilities={"darkweb_discovery", "onion_discovery", "email", "domain", "username", "crypto_address"}, transport=Transport.TOR_HTTP, access=Access.MANUAL_ASSISTED, origin=Origin.DARKWEB_PUBLICATION, global_scope=True, default_enabled=False, sensitivity=DataSensitivity.DARKWEB_PUBLIC, documentation_url="https://support.torproject.org/tor-browser/features/onion-services/", notes="R13.14 bounded public-v3-onion discovery. Ahmia safety blocklist is required by default; no login, POST, redirect following, file download or raw page storage."),
    _source("intelligencex_search", "Intelligence X — Metadata Search", categories={Category.BREACH_INTELLIGENCE, Category.DARK_WEB, Category.WEB_OSINT}, capabilities={"email", "domain", "url", "ip", "phone", "crypto_address", "breach_lookup", "darkweb_index"}, transport=Transport.REST, access=Access.CONTRACT, cost=Cost.PAID, origin=Origin.AGGREGATOR, global_scope=True, requires_credentials=True, default_enabled=False, sensitivity=DataSensitivity.BREACH_METADATA, documentation_url="https://help.intelx.io/api/", terms_url="https://intelx.io/terms", notes="R13.12 metadata-only adapter. Underlying indexed document contents are not fetched, previewed, exported or persisted."),
    _source("hibp_pastes", "Have I Been Pwned — Paste Metadata", categories={Category.BREACH_INTELLIGENCE}, capabilities={"email", "paste_exposure"}, access=Access.CONTRACT, cost=Cost.MIXED, origin=Origin.BREACH_PROVIDER, global_scope=True, requires_credentials=True, default_enabled=False, sensitivity=DataSensitivity.BREACH_METADATA, documentation_url="https://haveibeenpwned.com/API/v3", notes="Paste metadata only; paste bodies are not fetched by R13.13."),
    _source("hibp_verified_domain", "Have I Been Pwned — Verified Domain Exposure", categories={Category.BREACH_INTELLIGENCE}, capabilities={"verified_domain_breach", "domain_exposure"}, access=Access.VERIFIED_SCOPE, cost=Cost.MIXED, origin=Origin.BREACH_PROVIDER, global_scope=True, requires_credentials=True, default_enabled=False, sensitivity=DataSensitivity.RESTRICTED, documentation_url="https://haveibeenpwned.com/API/v3", notes="Requires explicit verified_scope and server-side HIBP subscribed-domain verification."),
    _source("hibp_stealer_logs_email", "Have I Been Pwned — Stealer Logs by Email", categories={Category.BREACH_INTELLIGENCE}, capabilities={"stealer_log_email"}, access=Access.VERIFIED_SCOPE, cost=Cost.PAID, origin=Origin.BREACH_PROVIDER, global_scope=True, requires_credentials=True, default_enabled=False, sensitivity=DataSensitivity.RESTRICTED, documentation_url="https://haveibeenpwned.com/API/v3", notes="Verified-domain scope only. HIBP returns affected website domains, not passwords."),
    _source("hibp_stealer_logs_email_domain", "Have I Been Pwned — Stealer Logs by Email Domain", categories={Category.BREACH_INTELLIGENCE}, capabilities={"stealer_log_email_domain"}, access=Access.VERIFIED_SCOPE, cost=Cost.PAID, origin=Origin.BREACH_PROVIDER, global_scope=True, requires_credentials=True, default_enabled=False, sensitivity=DataSensitivity.RESTRICTED, documentation_url="https://haveibeenpwned.com/API/v3", notes="Verified-domain scope only; raw credentials are not returned or persisted."),
    _source("hibp_stealer_logs_website_domain", "Have I Been Pwned — Stealer Logs by Website Domain", categories={Category.BREACH_INTELLIGENCE}, capabilities={"stealer_log_website_domain"}, access=Access.VERIFIED_SCOPE, cost=Cost.PAID, origin=Origin.BREACH_PROVIDER, global_scope=True, requires_credentials=True, default_enabled=False, sensitivity=DataSensitivity.RESTRICTED, documentation_url="https://haveibeenpwned.com/API/v3", notes="Verified website-domain scope only; raw credentials are not returned or persisted."),
    _source("github_secret_scanning", "GitHub Secret Scanning — Authorized Repository Alerts", categories={Category.BREACH_INTELLIGENCE, Category.WEB_OSINT}, capabilities={"repository_secret_exposure"}, access=Access.VERIFIED_SCOPE, cost=Cost.MIXED, origin=Origin.OFFICIAL_API, global_scope=True, requires_credentials=True, default_enabled=False, sensitivity=DataSensitivity.RESTRICTED, documentation_url="https://docs.github.com/en/rest/secret-scanning/secret-scanning", notes="Authorized repository scope only. Requests hide_secret=true and discards any literal secret field defensively."),

    # ---------------- Existing OSINT connectors / remote web sources --------
    _source("common_crawl", "Common Crawl Index", categories={Category.ARCHIVE, Category.WEB_OSINT}, capabilities={"url", "domain", "historical_web"}, origin=Origin.COMMUNITY_INDEX, global_scope=True, documentation_url="https://index.commoncrawl.org/"),
    _source("crt_sh", "crt.sh Certificate Transparency", categories={Category.WEB_OSINT}, capabilities={"domain", "certificate", "subdomain"}, origin=Origin.COMMUNITY_INDEX, global_scope=True, documentation_url="https://crt.sh/"),
    _source("urlscan", "urlscan.io", categories={Category.THREAT_INTELLIGENCE, Category.WEB_OSINT}, capabilities={"url", "domain", "ip", "scan"}, access=Access.FREE_API_KEY, origin=Origin.AGGREGATOR, global_scope=True, requires_credentials=True, documentation_url="https://urlscan.io/docs/api/"),
    _source("virustotal", "VirusTotal", categories={Category.THREAT_INTELLIGENCE}, capabilities={"domain", "url", "ip", "hash"}, access=Access.FREE_API_KEY, origin=Origin.AGGREGATOR, global_scope=True, requires_credentials=True, documentation_url="https://docs.virustotal.com/reference/overview"),
    _source("alienvault_otx", "AlienVault OTX", categories={Category.THREAT_INTELLIGENCE}, capabilities={"domain", "url", "ip", "hash", "pulse"}, access=Access.FREE_API_KEY, origin=Origin.AGGREGATOR, global_scope=True, requires_credentials=True, documentation_url="https://otx.alienvault.com/api"),
    _source("greynoise", "GreyNoise", categories={Category.THREAT_INTELLIGENCE}, capabilities={"ip", "internet_scanner_context"}, access=Access.FREE_API_KEY, cost=Cost.MIXED, origin=Origin.AGGREGATOR, global_scope=True, requires_credentials=True, documentation_url="https://docs.greynoise.io/"),
    _source("abuseipdb", "AbuseIPDB", categories={Category.THREAT_INTELLIGENCE}, capabilities={"ip", "abuse_report"}, access=Access.FREE_API_KEY, cost=Cost.MIXED, origin=Origin.AGGREGATOR, global_scope=True, requires_credentials=True, documentation_url="https://docs.abuseipdb.com/"),
    _source("bgpview", "BGPView", categories={Category.THREAT_INTELLIGENCE, Category.WEB_OSINT}, capabilities={"ip", "asn", "prefix", "organization"}, origin=Origin.AGGREGATOR, global_scope=True, documentation_url="https://bgpview.io/"),
    _source("wayback_cdx", "Internet Archive Wayback CDX", categories={Category.ARCHIVE, Category.WEB_OSINT}, capabilities={"url", "domain", "historical_web"}, origin=Origin.COMMUNITY_INDEX, global_scope=True, documentation_url="https://web.archive.org/"),
    _source("gdelt", "GDELT", categories={Category.OPEN_DATA, Category.WEB_OSINT}, capabilities={"news", "name", "domain", "event"}, origin=Origin.COMMUNITY_INDEX, global_scope=True, documentation_url="https://www.gdeltproject.org/"),

    # ---------------- New official / open remote candidates -----------------
    _source("us_sec_edgar", "US SEC EDGAR", categories={Category.SECURITIES, Category.FINANCIAL, Category.REGISTRY}, capabilities={"cik", "company_filings", "xbrl", "securities"}, origin=Origin.OFFICIAL_API, countries={"US"}, documentation_url="https://www.sec.gov/search-filings/edgar-application-programming-interfaces"),
    _source("us_sam_entities", "SAM.gov Entity Management", categories={Category.REGISTRY, Category.PROCUREMENT}, capabilities={"uei", "entity", "registration_id", "company_name"}, access=Access.FREE_API_KEY, origin=Origin.OFFICIAL_API, countries={"US"}, requires_credentials=True, documentation_url="https://open.gsa.gov/api/entity-api/"),
    _source("us_sam_exclusions", "SAM.gov Exclusions", categories={Category.SANCTIONS, Category.PROCUREMENT}, capabilities={"name", "uei", "exclusion"}, access=Access.FREE_API_KEY, origin=Origin.OFFICIAL_API, countries={"US"}, requires_credentials=True, sensitivity=DataSensitivity.PUBLIC_SENSITIVE, documentation_url="https://open.gsa.gov/api/exclusions-api/"),
    _source("us_sam_opportunities", "SAM.gov Contract Opportunities", categories={Category.PROCUREMENT}, capabilities={"notice", "organization", "solicitation", "procurement"}, access=Access.FREE_API_KEY, origin=Origin.OFFICIAL_API, countries={"US"}, requires_credentials=True, documentation_url="https://open.gsa.gov/api/get-opportunities-public-api/"),
    _source("us_trade_csl", "US Consolidated Screening List", categories={Category.SANCTIONS}, capabilities={"name", "organization", "person", "screening", "fuzzy_name"}, access=Access.FREE_API_KEY, origin=Origin.OFFICIAL_API, countries={"US"}, requires_credentials=True, sensitivity=DataSensitivity.PUBLIC_SENSITIVE, documentation_url="https://www.trade.gov/consolidated-screening-list"),
    _source("eu_ted_search", "EU TED Procurement Search", categories={Category.PROCUREMENT, Category.OPEN_DATA}, capabilities={"notice", "buyer", "supplier", "procurement", "organization"}, origin=Origin.OFFICIAL_API, global_scope=True, documentation_url="https://docs.ted.europa.eu/api/latest/search.html"),
    _source("no_brreg_entities", "Norway Brønnøysund Entity Register", categories={Category.REGISTRY}, capabilities={"organization_number", "company_name", "organization"}, origin=Origin.OFFICIAL_API, countries={"NO"}, documentation_url="https://data.brreg.no/enhetsregisteret/api/dokumentasjon/en/index.html"),
    _source("no_brreg_roles", "Norway Brønnøysund Roles", categories={Category.REGISTRY, Category.PUBLIC_OFFICIAL}, capabilities={"organization_number", "role", "person", "organization"}, origin=Origin.OFFICIAL_API, countries={"NO"}, sensitivity=DataSensitivity.PUBLIC_SENSITIVE, documentation_url="https://data.brreg.no/"),
    _source("cz_ares", "Czech ARES", categories={Category.REGISTRY}, capabilities={"ico", "company_name", "organization", "address"}, origin=Origin.OFFICIAL_API, countries={"CZ"}, documentation_url="https://ares.gov.cz/"),
    _source("fr_sirene", "France Recherche d’entreprises (SIRENE/RNE)", categories={Category.REGISTRY}, capabilities={"siren", "siret", "company_name", "organization"}, access=Access.NO_AUTH, origin=Origin.OFFICIAL_API, countries={"FR"}, default_enabled=True, documentation_url="https://recherche-entreprises.api.gouv.fr/docs/"),
    _source("au_abn_lookup", "Australia ABN Lookup", categories={Category.REGISTRY}, capabilities={"abn", "acn", "company_name", "organization"}, transport=Transport.SOAP, access=Access.FREE_API_KEY, origin=Origin.OFFICIAL_API, countries={"AU"}, requires_credentials=True, documentation_url="https://abr.business.gov.au/Documentation/Default"),
    _source("ca_federal_corporations", "Corporations Canada Federal Corporation API", categories={Category.REGISTRY}, capabilities={"corporation_id", "business_number", "company", "director"}, access=Access.FREE_API_KEY, origin=Origin.OFFICIAL_API, countries={"CA"}, requires_credentials=True, sensitivity=DataSensitivity.PUBLIC_SENSITIVE, documentation_url="https://api.ised-isde.canada.ca/en/docs?api=corporations"),
    _source("uk_charity_commission", "UK Charity Commission Register", categories={Category.CHARITY, Category.REGISTRY}, capabilities={"charity_name", "charity_number", "trustee", "organization"}, access=Access.FREE_API_KEY, origin=Origin.OFFICIAL_API, countries={"GB"}, requires_credentials=True, sensitivity=DataSensitivity.PUBLIC_SENSITIVE, documentation_url="https://api-portal.charitycommission.gov.uk/"),
    _source("uk_sanctions_search", "UK Sanctions List Search", categories={Category.SANCTIONS}, capabilities={"name", "organization", "person", "ship", "sanctions"}, transport=Transport.PUBLIC_HTTP, access=Access.MANUAL_ASSISTED, origin=Origin.OFFICIAL_PORTAL, countries={"GB"}, sensitivity=DataSensitivity.PUBLIC_SENSITIVE, documentation_url="https://www.gov.uk/government/publications/the-uk-sanctions-list"),
    _source("pl_regon", "Poland REGON BIR1", categories={Category.REGISTRY}, capabilities={"regon", "nip", "krs", "organization"}, transport=Transport.SOAP, access=Access.FREE_API_KEY, origin=Origin.OFFICIAL_API, countries={"PL"}, requires_credentials=True, documentation_url="https://api.stat.gov.pl/Home/RegonApi?lang=en"),
    _source("crossref", "Crossref REST API", categories={Category.ACADEMIC, Category.OPEN_DATA}, capabilities={"doi", "work", "author", "funder", "orcid", "ror", "publication"}, origin=Origin.AGGREGATOR, global_scope=True, documentation_url="https://www.crossref.org/documentation/retrieve-metadata/rest-api/"),
    _source("ror", "Research Organization Registry", categories={Category.ACADEMIC, Category.REGISTRY}, capabilities={"organization", "ror_id", "affiliation", "name"}, origin=Origin.AGGREGATOR, global_scope=True, documentation_url="https://ror.readme.io/docs/rest-api"),
    _source("openalex", "OpenAlex", categories={Category.ACADEMIC, Category.OPEN_DATA}, capabilities={"work", "author", "institution", "source", "topic", "name"}, origin=Origin.AGGREGATOR, global_scope=True, documentation_url="https://help.openalex.org/api/"),
    _source("orcid_public", "ORCID Anonymous/Public API", categories={Category.ACADEMIC, Category.OPEN_DATA}, capabilities={"orcid", "person", "researcher", "name"}, access=Access.NO_AUTH, origin=Origin.AGGREGATOR, global_scope=True, default_enabled=True, sensitivity=DataSensitivity.PUBLIC_SENSITIVE, documentation_url="https://info.orcid.org/documentation/api-tutorials/api-tutorial-searching-the-orcid-registry/", notes="R13.15 uses the read-only anonymous/public expanded-search endpoint. Name matches remain candidates until independently resolved."),
    _source("wikidata_sparql", "Wikidata Query Service", categories={Category.OPEN_DATA, Category.WEB_OSINT}, capabilities={"person", "organization", "identifier", "relationship", "location", "name"}, transport=Transport.SPARQL, origin=Origin.COMMUNITY_INDEX, global_scope=True, documentation_url="https://query.wikidata.org/"),
    _source("wikidata_search", "Wikidata Entity Search", categories={Category.OPEN_DATA, Category.WEB_OSINT}, capabilities={"person", "organization", "location", "name", "entity_search", "wikidata_id"}, transport=Transport.PUBLIC_HTTP, access=Access.NO_AUTH, origin=Origin.COMMUNITY_INDEX, global_scope=True, default_enabled=True, documentation_url="https://www.wikidata.org/wiki/Wikidata:Data_access", notes="R13.15 uses the official entity-search API for text discovery and exact QID fetches; fuzzy/name hits are candidate-only."),
    _source("nvd_cve_api", "NIST NVD CVE API", categories={Category.THREAT_INTELLIGENCE, Category.OPEN_DATA}, capabilities={"cve", "cve_id", "vulnerability", "product", "vendor", "keyword"}, access=Access.NO_AUTH, origin=Origin.OFFICIAL_API, countries={"US"}, default_enabled=True, documentation_url="https://nvd.nist.gov/developers/vulnerabilities", notes="NVD API key is optional in R13.15 and can be supplied only to improve public API rate limits."),
    _source("openfda", "openFDA", categories={Category.OPEN_DATA, Category.PROFESSIONAL}, capabilities={"manufacturer", "organization", "product", "device", "drug", "enforcement"}, access=Access.NO_AUTH, origin=Origin.OFFICIAL_API, countries={"US"}, default_enabled=True, documentation_url="https://open.fda.gov/apis/", notes="Works without an API key at public anonymous limits; optional free key raises quota."),
    _source("us_fec", "US Federal Election Commission API", categories={Category.PUBLIC_OFFICIAL, Category.OPEN_DATA}, capabilities={"candidate", "committee", "organization", "contribution", "contributor", "name"}, access=Access.NO_AUTH, origin=Origin.OFFICIAL_API, countries={"US"}, default_enabled=True, sensitivity=DataSensitivity.PUBLIC_SENSITIVE, documentation_url="https://api.open.fec.gov/developers/", notes="R13.15 falls back to the documented DEMO_KEY; a free user API key is optional. Street-address fields are not retained by the adapter."),
    _source("opensanctions", "OpenSanctions", categories={Category.SANCTIONS, Category.PUBLIC_OFFICIAL}, capabilities={"person", "organization", "sanctions", "pep", "name"}, access=Access.FREE_API_KEY, cost=Cost.MIXED, origin=Origin.AGGREGATOR, global_scope=True, requires_credentials=True, sensitivity=DataSensitivity.PUBLIC_SENSITIVE, documentation_url="https://www.opensanctions.org/docs/api/"),
    _source("icij_offshore_leaks", "ICIJ Offshore Leaks Database", categories={Category.OPEN_DATA, Category.REGISTRY}, capabilities={"name", "person", "organization", "offshore_entity", "officer", "intermediary", "address"}, transport=Transport.REST, access=Access.NO_AUTH, origin=Origin.COMMUNITY_INDEX, global_scope=True, default_enabled=False, sensitivity=DataSensitivity.PUBLIC_SENSITIVE, documentation_url="https://offshoreleaks.icij.org/docs/reconciliation", notes="R13.15 uses the official reconciliation API. Results are investigative candidates only and never automatic proof of identity or offshore involvement."),
    _source("us_nppes_npi", "US NPPES / NPI Registry", categories={Category.PROFESSIONAL, Category.OPEN_DATA}, capabilities={"npi", "provider", "person", "organization", "name"}, transport=Transport.REST, access=Access.NO_AUTH, origin=Origin.OFFICIAL_API, countries={"US"}, default_enabled=True, sensitivity=DataSensitivity.PUBLIC_SENSITIVE, documentation_url="https://npiregistry.cms.hhs.gov/api-page", notes="Public NPI directory. NPI issuance does not validate licensure or credentials; name matches remain candidates."),
    _source("github_public_user", "GitHub Public User API", categories={Category.WEB_OSINT, Category.OPEN_DATA}, capabilities={"username", "github_username"}, transport=Transport.REST, access=Access.NO_AUTH, origin=Origin.OFFICIAL_API, global_scope=True, default_enabled=True, sensitivity=DataSensitivity.PUBLIC_SENSITIVE, documentation_url="https://docs.github.com/en/rest/users/users", notes="Exact public account lookup only. A platform account is not automatically resolved to a real-world person."),
    _source("gitlab_public_user", "GitLab Public Users API", categories={Category.WEB_OSINT, Category.OPEN_DATA}, capabilities={"username", "gitlab_username"}, transport=Transport.REST, access=Access.NO_AUTH, origin=Origin.OFFICIAL_API, global_scope=True, default_enabled=True, sensitivity=DataSensitivity.PUBLIC_SENSITIVE, documentation_url="https://docs.gitlab.com/api/users/", notes="Exact public username lookup; account-to-person identity inference remains prohibited."),
    _source("semantic_scholar", "Semantic Scholar Academic Graph", categories={Category.ACADEMIC, Category.OPEN_DATA}, capabilities={"academic_author", "author", "paper", "publication"}, transport=Transport.REST, access=Access.NO_AUTH, origin=Origin.AGGREGATOR, global_scope=True, default_enabled=True, sensitivity=DataSensitivity.PUBLIC_SENSITIVE, documentation_url="https://www.semanticscholar.org/product/api", notes="Public Academic Graph API; author name matches remain candidates."),
    _source("europe_pmc", "Europe PMC REST API", categories={Category.ACADEMIC, Category.OPEN_DATA}, capabilities={"publication", "author", "academic_author", "doi", "pmid"}, transport=Transport.REST, access=Access.NO_AUTH, origin=Origin.AGGREGATOR, global_scope=True, default_enabled=True, sensitivity=DataSensitivity.PUBLIC_SENSITIVE, documentation_url="https://europepmc.org/RestfulWebService", notes="Public publication metadata API; no article files are downloaded by R13.16."),
    _source("library_of_congress", "Library of Congress JSON API", categories={Category.ARCHIVE, Category.OPEN_DATA}, capabilities={"archive_search", "historical_document", "historical_web"}, transport=Transport.REST, access=Access.NO_AUTH, origin=Origin.OFFICIAL_API, global_scope=True, default_enabled=True, documentation_url="https://www.loc.gov/apis/json-and-yaml/", notes="Metadata-only search. R13.16 never downloads media/resources from Library collections."),
    _source("fbi_wanted", "FBI Wanted Public API", categories={Category.OPEN_DATA}, capabilities={"wanted_person", "wanted_name"}, transport=Transport.REST, access=Access.NO_AUTH, origin=Origin.OFFICIAL_API, countries={"US"}, default_enabled=False, sensitivity=DataSensitivity.PUBLIC_SENSITIVE, documentation_url="https://www.fbi.gov/wanted/api", notes="Public notice candidates only. Results are never treated as proof of identity, guilt, conviction or legal outcome."),
    _source("first_epss", "FIRST EPSS API", categories={Category.THREAT_INTELLIGENCE, Category.OPEN_DATA}, capabilities={"cve", "cve_id", "epss"}, transport=Transport.REST, access=Access.NO_AUTH, origin=Origin.COMMUNITY_INDEX, global_scope=True, default_enabled=True, documentation_url="https://api.first.org/epss/", notes="Exact CVE exploit-probability lookup with no local dataset download."),
    _source("circl_hashlookup", "CIRCL hashlookup", categories={Category.THREAT_INTELLIGENCE, Category.OPEN_DATA}, capabilities={"hash", "md5", "sha1", "sha256"}, transport=Transport.REST, access=Access.NO_AUTH, origin=Origin.COMMUNITY_INDEX, global_scope=True, default_enabled=True, documentation_url="https://circl.lu/services/hashlookup/", notes="Exact hash context lookup against public known-file datasets; a match is not itself a maliciousness verdict."),
    _source("shodan_internetdb", "Shodan InternetDB", categories={Category.THREAT_INTELLIGENCE, Category.WEB_OSINT}, capabilities={"ip", "ip_address", "open_ports", "vulnerability"}, transport=Transport.REST, access=Access.NO_AUTH, origin=Origin.AGGREGATOR, global_scope=True, default_enabled=True, documentation_url="https://internetdb.shodan.io/", notes="Free low-detail IP snapshot: ports, CPEs, hostnames, tags and vulnerability identifiers; no banners are returned."),
    _source("cisa_kev", "CISA Known Exploited Vulnerabilities", categories={Category.THREAT_INTELLIGENCE, Category.OPEN_DATA}, capabilities={"cve", "cve_id", "known_exploited"}, transport=Transport.PUBLIC_HTTP, access=Access.NO_AUTH, origin=Origin.OFFICIAL_API, global_scope=True, default_enabled=True, documentation_url="https://www.cisa.gov/known-exploited-vulnerabilities-catalog", notes="Exact CVE lookup. The small JSON catalog is read transiently in memory and is never persisted by R13.16."),
    _source("rdap_bootstrap", "RDAP.org Bootstrap", categories={Category.WEB_OSINT, Category.OPEN_DATA}, capabilities={"domain", "domain_rdap", "ip", "ip_address", "ip_rdap", "asn", "autonomous_system", "asn_rdap"}, transport=Transport.REST, access=Access.NO_AUTH, origin=Origin.AGGREGATOR, global_scope=True, default_enabled=True, documentation_url="https://about.rdap.org/", notes="Exact domain/IP/ASN RDAP lookup. Raw vCard/contact structures are not retained by the adapter."),
    _source("ripestat", "RIPEstat Data API", categories={Category.WEB_OSINT, Category.OPEN_DATA, Category.THREAT_INTELLIGENCE}, capabilities={"ip", "ip_address", "asn", "autonomous_system", "network_registration"}, transport=Transport.REST, access=Access.NO_AUTH, origin=Origin.OFFICIAL_API, global_scope=True, default_enabled=True, documentation_url="https://stat.ripe.net/docs/data-api/ripestat-data-api", notes="Exact IP/ASN network metadata; no local RIPE dataset replication."),
    _source("peeringdb_public", "PeeringDB Guest API", categories={Category.WEB_OSINT, Category.OPEN_DATA}, capabilities={"asn", "autonomous_system", "peering_network"}, transport=Transport.REST, access=Access.NO_AUTH, origin=Origin.COMMUNITY_INDEX, global_scope=True, default_enabled=True, documentation_url="https://docs.peeringdb.com/api_specs/", notes="Guest exact-ASN queries only; restricted contact data is not requested."),
    _source("google_public_dns", "Google Public DNS JSON API", categories={Category.WEB_OSINT, Category.OPEN_DATA}, capabilities={"domain", "dns", "domain_dns"}, transport=Transport.REST, access=Access.NO_AUTH, origin=Origin.AGGREGATOR, global_scope=True, default_enabled=True, documentation_url="https://developers.google.com/speed/public-dns/docs/doh/json", notes="Bounded DNS record lookup; no persistent DNS cache is created by R13.17."),
    _source("usaspending_recipients", "USAspending Recipient API", categories={Category.PROCUREMENT, Category.FINANCIAL, Category.OPEN_DATA}, capabilities={"recipient", "organization", "uei", "duns", "federal_award_recipient"}, transport=Transport.REST, access=Access.NO_AUTH, origin=Origin.OFFICIAL_API, countries={"US"}, default_enabled=True, sensitivity=DataSensitivity.PUBLIC_SENSITIVE, documentation_url="https://api.usaspending.gov/docs/endpoints", notes="Public federal-award recipient search. Name matches are candidates until independently resolved."),
    _source("us_federal_register", "US Federal Register API", categories={Category.OPEN_DATA, Category.ARCHIVE, Category.PUBLIC_OFFICIAL}, capabilities={"federal_register", "regulatory_document", "regulation_search", "name", "organization", "keyword"}, transport=Transport.REST, access=Access.NO_AUTH, origin=Origin.OFFICIAL_API, countries={"US"}, default_enabled=True, sensitivity=DataSensitivity.PUBLIC_SENSITIVE, documentation_url="https://www.federalregister.gov/developers/documentation/api/v1", notes="Document metadata/mention search only; linked PDFs are not downloaded."),
    _source("datacite_public", "DataCite Public API", categories={Category.ACADEMIC, Category.OPEN_DATA}, capabilities={"doi", "publication", "dataset", "research_output", "author"}, transport=Transport.REST, access=Access.NO_AUTH, origin=Origin.AGGREGATOR, global_scope=True, default_enabled=True, sensitivity=DataSensitivity.PUBLIC_SENSITIVE, documentation_url="https://support.datacite.org/docs/rest-api", notes="Public DOI metadata retrieval; linked research files are not downloaded."),
    _source("zenodo_public", "Zenodo Public Records API", categories={Category.ACADEMIC, Category.OPEN_DATA, Category.ARCHIVE}, capabilities={"research_output", "publication", "dataset", "software", "doi", "author"}, transport=Transport.REST, access=Access.NO_AUTH, origin=Origin.AGGREGATOR, global_scope=True, default_enabled=True, sensitivity=DataSensitivity.PUBLIC_SENSITIVE, documentation_url="https://developers.zenodo.org/", notes="Anonymous published-record metadata search; files are not downloaded."),
    _source("internet_archive_metadata", "Internet Archive Metadata Search", categories={Category.ARCHIVE, Category.OPEN_DATA}, capabilities={"archive_search", "internet_archive", "historical_document", "keyword", "name"}, transport=Transport.REST, access=Access.NO_AUTH, origin=Origin.COMMUNITY_INDEX, global_scope=True, default_enabled=True, sensitivity=DataSensitivity.PUBLIC_SENSITIVE, documentation_url="https://archive.org/advancedsearch.php", notes="Advanced Search item metadata only; item content/media are not downloaded."),
    _source("un_sc_sanctions", "UN Security Council Consolidated Sanctions List", categories={Category.SANCTIONS, Category.PUBLIC_OFFICIAL}, capabilities={"sanctions_name", "sanctions_entity", "un_sanctions"}, transport=Transport.PUBLIC_HTTP, access=Access.NO_AUTH, origin=Origin.OFFICIAL_OPEN_DATA, global_scope=True, default_enabled=False, sensitivity=DataSensitivity.PUBLIC_SENSITIVE, documentation_url="https://main.un.org/securitycouncil/en/content/un-sc-consolidated-list", notes="Explicit sanctions search only. Small official XML is processed transiently and not persisted; name matches are not identity confirmation or proof of guilt."),
)


COVERAGE_ENTRIES: tuple[SourceCoverageEntry, ...] = (
    SourceCoverageEntry("gleif_lei", Status.ACTIVE, "GleifRegistryProvider", "R6"),
    SourceCoverageEntry("eu_vies", Status.ACTIVE, "ViesRegistryProvider", "R7"),
    SourceCoverageEntry("opencorporates", Status.ACTIVE, "OpenCorporatesRegistryProvider", "R5"),
    SourceCoverageEntry("ua_edr_business", Status.ACTIVE, "RemoteRegistryProvider", "R8"),
    SourceCoverageEntry("ua_edrsr", Status.ACTIVE, "RemoteRegistryProvider", "R9"),
    SourceCoverageEntry("courtlistener", Status.ACTIVE, "CourtListenerRegistryProvider", "R10"),
    SourceCoverageEntry("courtlistener_recap", Status.ACTIVE, "CourtListenerRecapRegistryProvider", "R11"),
    SourceCoverageEntry("uk_companies_house", Status.ACTIVE, "CompaniesHouseRegistryProvider", "R12"),
    SourceCoverageEntry("pl_krs", Status.ACTIVE, "PolandKrsRegistryProvider", "R13"),
    SourceCoverageEntry("hibp_breached_account", Status.ACTIVE, "BreachIntelligenceService", "R13.6"),
    SourceCoverageEntry("hibp_pwned_passwords", Status.ACTIVE, "BreachIntelligenceService", "R13.6"),
    SourceCoverageEntry("tor_public_onion_fetch", Status.ACTIVE, "DarkWebIntelligenceService", "R13.7"),
    SourceCoverageEntry("tor_onion_discovery", Status.ACTIVE, "DarkWebDiscoveryService", "R13.14 bounded crawl + Ahmia safety filter"),
    SourceCoverageEntry("intelligencex_search", Status.ACTIVE, "IntelligenceXMetadataAdapter", "R13.12 metadata-only; credential-gated"),
    SourceCoverageEntry("hibp_pastes", Status.ACTIVE, "HibpPasteAdapter", "R13.13 metadata-only; credential-gated"),
    SourceCoverageEntry("hibp_verified_domain", Status.ACTIVE, "HibpVerifiedDomainAdapter", "R13.13 verified-scope"),
    SourceCoverageEntry("hibp_stealer_logs_email", Status.ACTIVE, "HibpStealerLogEmailAdapter", "R13.13 verified-scope; Pro"),
    SourceCoverageEntry("hibp_stealer_logs_email_domain", Status.ACTIVE, "HibpStealerLogEmailDomainAdapter", "R13.13 verified-scope; Pro"),
    SourceCoverageEntry("hibp_stealer_logs_website_domain", Status.ACTIVE, "HibpStealerLogWebsiteDomainAdapter", "R13.13 verified-scope; Pro"),
    SourceCoverageEntry("github_secret_scanning", Status.ACTIVE, "GitHubSecretScanningAdapter", "R13.13 authorized-repository; hide-secret"),
    SourceCoverageEntry("common_crawl", Status.EXISTING_CONNECTOR, "CommonCrawl/OpenWeb", "existing"),
    SourceCoverageEntry("crt_sh", Status.EXISTING_CONNECTOR, "crt.sh connector", "existing"),
    SourceCoverageEntry("urlscan", Status.EXISTING_CONNECTOR, "URLScan connector", "existing"),
    SourceCoverageEntry("virustotal", Status.EXISTING_CONNECTOR, "VirusTotal connector", "existing"),
    SourceCoverageEntry("alienvault_otx", Status.EXISTING_CONNECTOR, "AlienVault OTX connector", "existing"),
    SourceCoverageEntry("greynoise", Status.EXISTING_CONNECTOR, "GreyNoise connector", "existing"),
    SourceCoverageEntry("abuseipdb", Status.EXISTING_CONNECTOR, "AbuseIPDB connector", "existing"),
    SourceCoverageEntry("bgpview", Status.EXISTING_CONNECTOR, "BGPView connector", "existing"),
    SourceCoverageEntry("wayback_cdx", Status.EXISTING_CONNECTOR, "Wayback connector", "existing"),
    SourceCoverageEntry("gdelt", Status.EXISTING_CONNECTOR, "OpenWeb GDELT", "existing"),
    SourceCoverageEntry("us_sec_edgar", Status.ACTIVE, "SecEdgarAdapter", "R13.10 exact-CIK"),
    SourceCoverageEntry("us_sam_entities", Status.ACTIVE, "SamGovEntityAdapter", "R13.10 credential-gated"),
    SourceCoverageEntry("us_sam_exclusions", Status.CATALOGED, stage="next-wave"),
    SourceCoverageEntry("us_sam_opportunities", Status.CATALOGED, stage="next-wave"),
    SourceCoverageEntry("us_trade_csl", Status.ACTIVE, "TradeCslAdapter", "R13.10 credential-gated screening"),
    SourceCoverageEntry("eu_ted_search", Status.ACTIVE, "TedSearchAdapter", "R13.10 expert-query"),
    SourceCoverageEntry("no_brreg_entities", Status.ACTIVE, "NorwayBrregAdapter", "R13.9"),
    SourceCoverageEntry("no_brreg_roles", Status.CATALOGED, stage="europe"),
    SourceCoverageEntry("cz_ares", Status.ACTIVE, "CzechAresAdapter", "R13.9 exact-ICO"),
    SourceCoverageEntry("fr_sirene", Status.ACTIVE, "FranceEnterpriseSearchAdapter", "R13.11 open DINUM search / SIRENE+RNE"),
    SourceCoverageEntry("au_abn_lookup", Status.ACTIVE, "AustraliaAbnLookupAdapter", "R13.11 credential-gated"),
    SourceCoverageEntry("ca_federal_corporations", Status.ACTIVE, "CanadaFederalCorporationsAdapter", "R13.11 exact identifiers; credential-gated"),
    SourceCoverageEntry("uk_charity_commission", Status.ACTIVE, "UkCharityCommissionAdapter", "R13.11 credential-gated"),
    SourceCoverageEntry("uk_sanctions_search", Status.MANUAL_ASSISTED, stage="next-wave"),
    SourceCoverageEntry("pl_regon", Status.ACTIVE, "PolandRegonAdapter", "R13.11 exact REGON/NIP/KRS; credential-gated"),
    SourceCoverageEntry("crossref", Status.ACTIVE, "CrossrefAdapter", "R13.9"),
    SourceCoverageEntry("ror", Status.ACTIVE, "RorAdapter", "R13.9"),
    SourceCoverageEntry("openalex", Status.ACTIVE, "OpenAlexAdapter", "R13.9 credential-gated"),
    SourceCoverageEntry("orcid_public", Status.ACTIVE, "OrcidPublicAdapter", "R13.15 anonymous/public search"),
    SourceCoverageEntry("wikidata_sparql", Status.CATALOGED, stage="global-open-data"),
    SourceCoverageEntry("nvd_cve_api", Status.ACTIVE, "NvdCveAdapter", "R13.15 no-key; optional free key"),
    SourceCoverageEntry("openfda", Status.ACTIVE, "OpenFdaAdapter", "R13.15 anonymous public API"),
    SourceCoverageEntry("us_fec", Status.ACTIVE, "OpenFecAdapter", "R13.15 DEMO_KEY/free-key"),
    SourceCoverageEntry("opensanctions", Status.CATALOGED, stage="sanctions"),
    SourceCoverageEntry("icij_offshore_leaks", Status.ACTIVE, "IcijOffshoreLeaksAdapter", "R13.15 reconciliation candidates"),
    SourceCoverageEntry("wikidata_search", Status.ACTIVE, "WikidataEntitySearchAdapter", "R13.15 public entity search"),
    SourceCoverageEntry("us_nppes_npi", Status.ACTIVE, "NppesNpiAdapter", "R13.15 public NPI API v2.1"),
    SourceCoverageEntry("github_public_user", Status.ACTIVE, "GitHubPublicUserAdapter", "R13.16 low-footprint remote"),
    SourceCoverageEntry("gitlab_public_user", Status.ACTIVE, "GitLabPublicUserAdapter", "R13.16 low-footprint remote"),
    SourceCoverageEntry("semantic_scholar", Status.ACTIVE, "SemanticScholarAdapter", "R13.16 low-footprint remote"),
    SourceCoverageEntry("europe_pmc", Status.ACTIVE, "EuropePmcAdapter", "R13.16 low-footprint remote"),
    SourceCoverageEntry("library_of_congress", Status.ACTIVE, "LibraryOfCongressAdapter", "R13.16 metadata-only archive search"),
    SourceCoverageEntry("fbi_wanted", Status.ACTIVE, "FbiWantedAdapter", "R13.16 explicit public-notice search"),
    SourceCoverageEntry("first_epss", Status.ACTIVE, "FirstEpssAdapter", "R13.16 exact CVE"),
    SourceCoverageEntry("circl_hashlookup", Status.ACTIVE, "CirclHashlookupAdapter", "R13.16 exact hash"),
    SourceCoverageEntry("shodan_internetdb", Status.ACTIVE, "ShodanInternetDbAdapter", "R13.16 free IP snapshot"),
    SourceCoverageEntry("cisa_kev", Status.ACTIVE, "CisaKevAdapter", "R13.16 transient exact-CVE feed lookup"),
    SourceCoverageEntry("rdap_bootstrap", Status.ACTIVE, "RdapBootstrapAdapter", "R13.17 exact domain/IP/ASN"),
    SourceCoverageEntry("ripestat", Status.ACTIVE, "RipeStatAdapter", "R13.17 network metadata"),
    SourceCoverageEntry("peeringdb_public", Status.ACTIVE, "PeeringDbAdapter", "R13.17 guest exact-ASN"),
    SourceCoverageEntry("google_public_dns", Status.ACTIVE, "GooglePublicDnsAdapter", "R13.17 bounded DNS JSON"),
    SourceCoverageEntry("usaspending_recipients", Status.ACTIVE, "UsaSpendingRecipientAdapter", "R13.17 recipient candidates"),
    SourceCoverageEntry("us_federal_register", Status.ACTIVE, "FederalRegisterAdapter", "R13.17 document mentions"),
    SourceCoverageEntry("datacite_public", Status.ACTIVE, "DataCiteAdapter", "R13.17 DOI metadata"),
    SourceCoverageEntry("zenodo_public", Status.ACTIVE, "ZenodoPublicAdapter", "R13.17 public record metadata"),
    SourceCoverageEntry("internet_archive_metadata", Status.ACTIVE, "InternetArchiveMetadataAdapter", "R13.17 metadata-only archive search"),
    SourceCoverageEntry("un_sc_sanctions", Status.ACTIVE, "UnSecurityCouncilSanctionsAdapter", "R13.17 explicit transient sanctions search"),
)


def register_massive_remote_sources(
    catalog: IntelligenceSourceCatalog,
) -> RemoteSourceCoverage:
    for source in MASSIVE_REMOTE_SOURCES:
        # R13.6/R13.7 may already have more specialized HIBP/Tor descriptors.
        # Preserve the existing installed descriptor instead of overwriting it.
        if catalog.get(source.code) is None:
            catalog.register(source)
    return RemoteSourceCoverage(COVERAGE_ENTRIES)
