"""
Search embedding indexer.

Builds and stores semantic vector representations for
existing SearchIndex records.

Architecture:

SearchIndexRepository
        ↓
SearchEmbeddingIndexer
        ↓
EmbeddingService
        ↓
Ollama / nomic-embed-text
        ↓
SearchEmbeddingRepository
        ↓
PostgreSQL + pgvector

Responsibilities:

- load searchable objects from SearchIndex
- build text representation for embeddings
- generate embeddings through EmbeddingService
- persist embeddings through SearchEmbeddingRepository
- skip already indexed objects when appropriate
- support forced re-indexing

Does NOT:

- perform semantic retrieval
- calculate vector similarity
- know about RankFusionService
- interact with UI
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Iterable
from uuid import UUID

from app.models.search_index import (
    SearchIndex,
)

from app.repositories.search_embedding_repository import (
    SearchEmbeddingRepository,
)

from app.repositories.search_index_repository import (
    SearchIndexRepository,
)

from app.services.embedding_service import (
    EmbeddingService,
)

from app.services.semantic_indexing_policy import (
    SemanticIndexingPolicy,
)


# ==========================================================
# Configuration
# ==========================================================


@dataclass(
    frozen=True,
    slots=True,
)
class SearchEmbeddingIndexerConfig:
    """
    Embedding indexing configuration.

    maximum_text_length:
        Safety limit for one searchable representation.

    title_repetitions:
        Small title boost in embedding representation.

        Semantic models do not use BM25 term frequency,
        so this is intentionally kept low.

    batch_size:
        Number of texts sent to EmbeddingService at once.
    """

    maximum_text_length: int = 20_000

    title_repetitions: int = 1

    batch_size: int = 16

    def __post_init__(
        self,
    ) -> None:

        if self.maximum_text_length < 1:

            raise ValueError(
                "maximum_text_length must "
                "be at least 1."
            )

        if self.title_repetitions < 1:

            raise ValueError(
                "title_repetitions must "
                "be at least 1."
            )

        if self.batch_size < 1:

            raise ValueError(
                "batch_size must be at least 1."
            )


# ==========================================================
# Indexing result
# ==========================================================


@dataclass(
    slots=True,
)
class SearchEmbeddingIndexResult:
    """
    Summary of one indexing operation.
    """

    processed: int = 0

    created_or_updated: int = 0

    skipped: int = 0

    failed: int = 0

    @property
    def successful(
        self,
    ) -> int:
        """
        Number of successfully handled indexes.
        """

        return (
            self.created_or_updated
            + self.skipped
        )


# ==========================================================
# Service
# ==========================================================


class SearchEmbeddingIndexer:
    """
    Creates semantic embeddings for SearchIndex records.
    """

    def __init__(
        self,
        *,
        search_index_repository: SearchIndexRepository,
        search_embedding_repository: SearchEmbeddingRepository,
        embedding_service: EmbeddingService,
        config: SearchEmbeddingIndexerConfig | None = None,
        semantic_indexing_policy: (
            SemanticIndexingPolicy
            | None
        ) = None,
    ) -> None:

        self.search_index_repository = (
            search_index_repository
        )

        self.search_embedding_repository = (
            search_embedding_repository
        )

        self.embedding_service = (
            embedding_service
        )

        self.config = (
            config
            or SearchEmbeddingIndexerConfig()
        )

        self.semantic_indexing_policy = (
            semantic_indexing_policy
            or SemanticIndexingPolicy()
        )

    # ======================================================
    # Case indexing
    # ======================================================

    def index_case(
        self,
        case_id: UUID,
        *,
        force: bool = False,
    ) -> SearchEmbeddingIndexResult:
        """
        Generate embeddings for all searchable indexes
        belonging to one investigation case.

        Existing embeddings generated by the same model
        are skipped unless force=True.
        """

        indexes = (
            self.search_index_repository
            .get_by_case(
                case_id
            )
        )

        return self.index_many(
            indexes,
            force=force,
        )

    # ======================================================
    # Multiple indexes
    # ======================================================

    def index_many(
        self,
        indexes: Iterable[
            SearchIndex
        ],
        *,
        force: bool = False,
    ) -> SearchEmbeddingIndexResult:
        """
        Generate embeddings for multiple SearchIndex rows.

        Optimized for large investigation cases.

        Existing embeddings are loaded once for the whole
        case/model instead of performing one SELECT query
        per SearchIndex row.
        """

        result = (
            SearchEmbeddingIndexResult()
        )

        # ------------------------------------------------------
        # Materialize indexes once
        # ------------------------------------------------------

        index_list = list(
            indexes
        )

        if not index_list:

            return result

        # ------------------------------------------------------
        # Load existing embeddings once
        # ------------------------------------------------------

        existing_search_index_ids: set[UUID] = (
            set()
        )

        if not force:

            case_ids = {
                index.case_id
                for index
                in index_list
            }

            for case_id in case_ids:

                existing_search_index_ids.update(
                    self.search_embedding_repository
                    .get_existing_search_index_ids(
                        case_id=case_id,
                        model=(
                            self.embedding_service
                            .model_name
                        ),
                    )
                )

        # ------------------------------------------------------
        # Prepare pending embeddings
        # ------------------------------------------------------

        pending: list[
            tuple[
                SearchIndex,
                str,
            ]
        ] = []

        for index in index_list:

            result.processed += 1

            # --------------------------------------------------
            # Deleted indexes
            # --------------------------------------------------

            if (
                getattr(
                    index,
                    "deleted_at",
                    None,
                )
                is not None
            ):

                result.skipped += 1

                continue

            # --------------------------------------------------
            # Existing embedding
            # --------------------------------------------------

            if (
                not force
                and index.id
                in existing_search_index_ids
            ):

                result.skipped += 1

                continue

            # --------------------------------------------------
            # Build semantic representation
            # --------------------------------------------------

            text = (
                self.build_embedding_text(
                    index
                )
            )

            if not text:

                result.skipped += 1

                continue

            # --------------------------------------------------
            # Semantic indexing policy
            # --------------------------------------------------

            decision = (
                self.semantic_indexing_policy
                .evaluate(
                    index,
                    text,
                )
            )

            if not decision.allowed:

                result.skipped += 1

                continue

            # --------------------------------------------------
            # Queue for batch processing
            # --------------------------------------------------

            pending.append(
                (
                    index,
                    text,
                )
            )

        # ------------------------------------------------------
        # Batch processing
        # ------------------------------------------------------

        for start in range(
            0,
            len(
                pending
            ),
            self.config.batch_size,
        ):

            batch = pending[
                start:
                start
                + self.config.batch_size
            ]

            self._index_batch(
                batch,
                result,
            )

        return result

    # ======================================================
    # One index
    # ======================================================

    def index_one(
        self,
        index: SearchIndex,
        *,
        force: bool = False,
    ) -> bool:
        """
        Generate or update one SearchIndex embedding.

        Returns True when an embedding was written.

        SemanticIndexingPolicy is applied before the
        embedding provider is called.
        """

        # ------------------------------------------------------
        # Deleted index
        # ------------------------------------------------------

        if (
            getattr(
                index,
                "deleted_at",
                None,
            )
            is not None
        ):

            return False

        # ------------------------------------------------------
        # Build semantic representation
        # ------------------------------------------------------

        text = (
            self.build_embedding_text(
                index
            )
        )

        if not text:

            return False

        # ------------------------------------------------------
        # Semantic indexing policy
        # ------------------------------------------------------

        decision = (
            self.semantic_indexing_policy
            .evaluate(
                index,
                text,
            )
        )

        if not decision.allowed:

            return False

        # ------------------------------------------------------
        # Existing embedding
        # ------------------------------------------------------

        if not force:

            existing = (
                self.search_embedding_repository
                .get_by_search_index(
                    search_index_id=(
                        index.id
                    ),
                    model=(
                        self.embedding_service
                        .model_name
                    ),
                )
            )

            if existing is not None:

                return False

        # ------------------------------------------------------
        # Generate embedding
        # ------------------------------------------------------

        embedding = (
            self.embedding_service.embed(
                text
            )
        )

        self._validate_dimensions(
            embedding.dimensions
        )

        # ------------------------------------------------------
        # Persist
        # ------------------------------------------------------

        self.search_embedding_repository.upsert(
            case_id=index.case_id,
            search_index_id=index.id,
            object_id=index.object_id,
            object_type=(
                self._object_type(
                    index
                )
            ),
            model=embedding.model,
            vector=embedding.vector,
        )

        return True

    # ======================================================
    # Batch indexing
    # ======================================================

    def _index_batch(
        self,
        batch: list[
            tuple[
                SearchIndex,
                str,
            ]
        ],
        result: SearchEmbeddingIndexResult,
    ) -> None:
        """
        Generate and persist one embedding batch.

        If the provider rejects the whole batch, retry
        individual records so one bad object does not
        destroy the rest of the indexing operation.
        """

        if not batch:

            return

        texts = [
            text
            for _, text
            in batch
        ]

        try:

            embeddings = (
                self.embedding_service
                .embed_many(
                    texts
                )
            )

            if (
                len(
                    embeddings
                )
                != len(
                    batch
                )
            ):

                raise RuntimeError(
                    "Embedding provider returned "
                    "an unexpected result count."
                )

        except Exception:

            self._index_batch_individually(
                batch,
                result,
            )

            return

        for (
            index,
            _
        ), embedding in zip(
            batch,
            embeddings,
        ):

            try:

                self._validate_dimensions(
                    embedding.dimensions
                )

                self.search_embedding_repository.upsert(
                    case_id=(
                        index.case_id
                    ),
                    search_index_id=(
                        index.id
                    ),
                    object_id=(
                        index.object_id
                    ),
                    object_type=(
                        self._object_type(
                            index
                        )
                    ),
                    model=(
                        embedding.model
                    ),
                    vector=(
                        embedding.vector
                    ),
                )

                result.created_or_updated += 1

            except Exception:

                result.failed += 1

    # ======================================================
    # Individual fallback
    # ======================================================

    def _index_batch_individually(
        self,
        batch: list[
            tuple[
                SearchIndex,
                str,
            ]
        ],
        result: SearchEmbeddingIndexResult,
    ) -> None:
        """
        Retry failed batch one record at a time.
        """

        for index, text in batch:

            try:

                embedding = (
                    self.embedding_service.embed(
                        text
                    )
                )

                self._validate_dimensions(
                    embedding.dimensions
                )

                self.search_embedding_repository.upsert(
                    case_id=(
                        index.case_id
                    ),
                    search_index_id=(
                        index.id
                    ),
                    object_id=(
                        index.object_id
                    ),
                    object_type=(
                        self._object_type(
                            index
                        )
                    ),
                    model=(
                        embedding.model
                    ),
                    vector=(
                        embedding.vector
                    ),
                )

                result.created_or_updated += 1

            except Exception:

                result.failed += 1

    # ======================================================
    # Embedding representation
    # ======================================================

    def build_embedding_text(
        self,
        index: SearchIndex,
    ) -> str:
        """
        Build semantic representation of SearchIndex.

        Message embeddings prioritize actual message text
        and human-readable conversational context.

        Technical fields such as UUIDs, external IDs,
        timestamps and raw metadata are intentionally
        excluded from message embeddings.
        """

        title = (
            index.title
            or ""
        ).strip()

        content = (
            index.content
            or ""
        ).strip()

        object_type = (
            self._object_type(
                index
            )
        )

        # ------------------------------------------------------
        # Message
        # ------------------------------------------------------

        if object_type == "message":

            message_text = (
                self._extract_structured_field(
                    content,
                    "MESSAGE_TEXT",
                )
            )

            sender = (
                self._extract_structured_field(
                    content,
                    "SENDER",
                )
            )

            receiver = (
                self._extract_structured_field(
                    content,
                    "RECEIVER",
                )
            )

            chat = (
                self._extract_structured_field(
                    content,
                    "CHAT",
                )
            )

            parts: list[str] = []

            if message_text:

                parts.append(
                    message_text
                )

            if sender:

                parts.append(
                    f"Sender: {sender}"
                )

            if receiver:

                parts.append(
                    f"Receiver: {receiver}"
                )

            if chat:

                parts.append(
                    f"Chat: {chat}"
                )

            text = "\n".join(
                parts
            ).strip()

            if not text:

                return ""

            return text[
                :self.config.maximum_text_length
            ]

        # ------------------------------------------------------
        # Other object types
        # ------------------------------------------------------

        parts: list[str] = []

        if title:

            parts.extend(
                [
                    title
                    for _ in range(
                        self.config
                        .title_repetitions
                    )
                ]
            )

        if content:

            parts.append(
                content
            )

        text = "\n".join(
            parts
        ).strip()

        if not text:

            return ""

        return text[
            :self.config.maximum_text_length
        ]

    # ======================================================
    # Helpers
    # ======================================================

    @staticmethod
    def _object_type(
        index: SearchIndex,
    ) -> str:
        """
        Normalize SearchIndex object type.
        """

        value = (
            index.object_type.value
            if hasattr(
                index.object_type,
                "value",
            )
            else str(
                index.object_type
            )
        )

        return (
            value
            .strip()
            .lower()
        )

    @staticmethod
    def _validate_dimensions(
        dimensions: int,
    ) -> None:
        """
        Ensure provider output matches current pgvector
        schema.

        nomic-embed-text was verified locally to return
        768-dimensional vectors.
        """

        if dimensions != 768:

            raise ValueError(
                "Semantic embedding dimension "
                "mismatch: expected 768, "
                f"got {dimensions}."
            )

    @staticmethod
    def _extract_structured_field(
        content: str,
        field_name: str,
    ) -> str:
        """
        Extract one field from structured SearchIndex
        content.
        """

        marker = (
            f"{field_name}:\n"
        )

        start = content.find(
            marker
        )

        if start < 0:

            return ""

        start += len(
            marker
        )

        remaining = content[
            start:
        ]

        end = remaining.find(
            "\n\n"
        )

        if end >= 0:

            remaining = remaining[
                :end
            ]

        return remaining.strip()