"""
Semantic search retriever.

Connects embedding-based vector retrieval with
UnifiedSearchService.

Architecture:

InvestigationSearchQuery
        ↓
SemanticSearchRetriever
        ↓
EmbeddingService
        ↓
query embedding
        ↓
SearchEmbeddingRepository
        ↓
pgvector cosine search
        ↓
InvestigationSearchHit[]
        ↓
UnifiedSearchService
        ↓
RRF

The retriever also supports receiving an already generated
query embedding. This allows a higher-level semantic
coordinator to reuse one query vector across multiple
semantic retrieval strategies.

Responsibilities:

- generate query embedding when used independently
- accept a precomputed query embedding
- perform case-scoped vector retrieval
- apply semantic similarity threshold
- convert vector matches into unified search hits
- preserve semantic provenance and distance metadata

Does NOT:

- generate stored document embeddings
- perform BM25
- perform fuzzy matching
- perform rank fusion
- interact with UI
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Protocol
from typing import Sequence

from app.investigation.search_query import (
    InvestigationSearchQuery,
    SearchMethod,
)

from app.investigation.search_result import (
    InvestigationSearchHit,
    SearchMatchReason,
    SearchScores,
)

from app.repositories.search_embedding_repository import (
    SearchEmbeddingRepository,
    SemanticVectorMatch,
)

from app.services.embedding_service import (
    EmbeddingService,
)

from app.services.search_retriever import (
    SearchRetriever,
    SearchRetrieverInfo,
)


# ==========================================================
# Shared query embedding contract
# ==========================================================


class SemanticQueryEmbedding(
    Protocol
):
    """
    Structural contract for a query embedding.

    Ollama embedding results already satisfy this protocol.

    A concrete embedding implementation is intentionally
    not required here so semantic retrievers stay decoupled
    from a specific embedding provider.
    """

    model: str

    vector: Sequence[
        float
    ]

    dimensions: int


# ==========================================================
# Configuration
# ==========================================================


@dataclass(
    frozen=True,
    slots=True,
)
class SemanticSearchRetrieverConfig:
    """
    Semantic retrieval configuration.

    minimum_similarity:
        default cosine similarity threshold.

    Values below the threshold are ignored before
    results reach RRF.
    """

    minimum_similarity: float = 0.30

    def __post_init__(
        self,
    ) -> None:

        if not (
            0.0
            <= self.minimum_similarity
            <= 1.0
        ):

            raise ValueError(
                "minimum_similarity must be "
                "between 0.0 and 1.0."
            )


# ==========================================================
# Retriever
# ==========================================================


class SemanticSearchRetriever(
    SearchRetriever
):
    """
    Semantic vector retriever backed by pgvector.

    It can operate in two modes:

    1. retrieve()
       Generates its own query embedding.

    2. retrieve_with_embedding()
       Reuses an embedding generated by a semantic
       coordinator.
    """

    def __init__(
        self,
        *,
        repository: SearchEmbeddingRepository,
        embedding_service: EmbeddingService,
        config: (
            SemanticSearchRetrieverConfig
            | None
        ) = None,
    ) -> None:

        self.repository = (
            repository
        )

        self.embedding_service = (
            embedding_service
        )

        self.config = (
            config
            or SemanticSearchRetrieverConfig()
        )

        self._info = SearchRetrieverInfo(
            name="semantic",
            method=SearchMethod.SEMANTIC,
            description=(
                "Semantic vector search using "
                "pgvector cosine similarity."
            ),
            enabled=True,
            priority=300,
        )

    # ======================================================
    # Retriever information
    # ======================================================

    @property
    def info(
        self,
    ) -> SearchRetrieverInfo:

        return self._info

    # ======================================================
    # Query compatibility
    # ======================================================

    def can_handle(
        self,
        query: InvestigationSearchQuery,
    ) -> bool:
        """
        Semantic search requires:

        - textual query
        - case scope
        """

        return (
            query.has_text_query
            and query.case_id is not None
        )

    # ======================================================
    # Standard retrieval
    # ======================================================

    def retrieve(
        self,
        query: InvestigationSearchQuery,
    ) -> list[
        InvestigationSearchHit
    ]:
        """
        Perform standalone semantic retrieval.

        This method preserves the original public API.

        When called directly, the retriever generates
        exactly one query embedding and delegates the
        remaining work to retrieve_with_embedding().
        """

        if not self.can_handle(
            query
        ):

            return []

        query_embedding = (
            self.embedding_service.embed(
                query.query
            )
        )

        return (
            self.retrieve_with_embedding(
                query=query,
                query_embedding=(
                    query_embedding
                ),
            )
        )

    # ======================================================
    # Shared-embedding retrieval
    # ======================================================

    def retrieve_with_embedding(
        self,
        *,
        query: InvestigationSearchQuery,
        query_embedding: (
            SemanticQueryEmbedding
        ),
        object_types: (
            Sequence[str]
            | None
        ) = None,
    ) -> list[
        InvestigationSearchHit
    ]:
        """
        Perform semantic retrieval using a query embedding
        that has already been generated.

        object_types:
            Optional internal override.

            When omitted, the object types from the
            InvestigationSearchQuery are used exactly as
            before.

            A future composite semantic retriever can pass
            only non-Message object types here so Message
            semantic search is handled exclusively by
            conversation chunks.

        No embedding provider call happens inside this
        method.
        """

        if not self.can_handle(
            query
        ):

            return []

        effective_object_types = (
            tuple(
                object_types
            )
            if object_types is not None
            else (
                query.object_types
                or None
            )
        )

        # --------------------------------------------------
        # Vector retrieval
        # --------------------------------------------------

        matches = (
            self.repository.search_similar(
                case_id=query.case_id,
                model=(
                    query_embedding.model
                ),
                query_vector=(
                    query_embedding.vector
                ),
                limit=(
                    query.candidate_limit
                ),
                object_types=(
                    effective_object_types
                ),
                object_ids=(
                    query.object_ids
                    or None
                ),
            )
        )

        # --------------------------------------------------
        # Threshold
        # --------------------------------------------------

        minimum_similarity = max(
            self.config.minimum_similarity,
            query.minimum_score,
        )

        hits: list[
            InvestigationSearchHit
        ] = []

        for match in matches:

            if (
                match.similarity
                < minimum_similarity
            ):

                continue

            hits.append(
                self._build_hit(
                    match
                )
            )

        return hits

    # ======================================================
    # Hit conversion
    # ======================================================

    def _build_hit(
        self,
        match: SemanticVectorMatch,
    ) -> InvestigationSearchHit:
        """
        Convert pgvector result into unified hit.
        """

        embedding = (
            match.embedding
        )

        search_index = (
            embedding.search_index
        )

        hit = InvestigationSearchHit(
            object_id=(
                embedding.object_id
            ),
            object_type=(
                embedding.object_type
            ),
            case_id=(
                embedding.case_id
            ),
            title=(
                search_index.title
                if search_index is not None
                else ""
            ),
            snippet=(
                self._build_snippet(
                    search_index
                )
            ),
            scores=SearchScores(
                semantic=(
                    match.similarity
                ),
            ),
            matched_methods=[
                SearchMethod.SEMANTIC,
            ],
            source=(
                search_index
                if search_index is not None
                else embedding
            ),
            metadata={
                "semantic_source": (
                    "search_index"
                ),
                "search_embedding_id": str(
                    embedding.id
                ),
                "search_index_id": str(
                    embedding.search_index_id
                ),
                "embedding_model": (
                    embedding.model
                ),
                "embedding_dimensions": (
                    embedding.dimensions
                ),
                "cosine_distance": (
                    match.distance
                ),
                "cosine_similarity": (
                    match.similarity
                ),
            },
        )

        hit.add_reason(
            SearchMatchReason(
                reason=(
                    self._build_reason(
                        match.similarity
                    )
                ),
                method=(
                    SearchMethod.SEMANTIC
                ),
                score=(
                    match.similarity
                ),
                details={
                    "semantic_source": (
                        "search_index"
                    ),
                    "cosine_distance": (
                        match.distance
                    ),
                    "cosine_similarity": (
                        match.similarity
                    ),
                    "model": (
                        embedding.model
                    ),
                },
            )
        )

        return hit

    # ======================================================
    # Explanation
    # ======================================================

    @staticmethod
    def _build_reason(
        similarity: float,
    ) -> str:
        """
        Build readable semantic match explanation.
        """

        if similarity >= 0.85:

            return (
                "Very strong semantic similarity."
            )

        if similarity >= 0.70:

            return (
                "Strong semantic similarity."
            )

        if similarity >= 0.50:

            return (
                "Moderate semantic similarity."
            )

        return (
            "Weak semantic similarity."
        )

    # ======================================================
    # Snippet
    # ======================================================

    @staticmethod
    def _build_snippet(
        search_index,
        *,
        maximum_length: int = 240,
    ) -> str:
        """
        Build compact semantic result snippet.
        """

        if search_index is None:

            return ""

        content = (
            search_index.content
            or ""
        ).strip()

        if not content:

            return (
                search_index.title
                or ""
            )

        if len(
            content
        ) <= maximum_length:

            return content

        return (
            content[
                :maximum_length
            ]
            .rstrip()
            + "..."
        )