"""Alembic migration environment for OSINT Intelligence Platform.

Architecture rule:

    SQLAlchemy models -> Base.metadata -> Alembic -> PostgreSQL

Database credentials are never stored in alembic.ini.  The migration CLI
uses the same Pydantic settings object as the application.
"""

from __future__ import annotations

from logging.config import fileConfig
from typing import Any

from alembic import context
from sqlalchemy import create_engine
from sqlalchemy import pool

# Import the central registry before reading Base.metadata so every ORM model
# is registered.  Do not replace this with per-model imports in migrations.
import app.models  # noqa: F401
from app.core.config import settings
from app.database.base import Base


config = context.config

if config.config_file_name is not None:
    fileConfig(config.config_file_name)


target_metadata = Base.metadata


# ---------------------------------------------------------------------------
# Autogenerate rendering
# ---------------------------------------------------------------------------


def _render_item(
    type_: str,
    obj: Any,
    autogen_context: Any,
) -> str | bool:
    """Render external SQLAlchemy types used by the project.

    pgvector is not part of SQLAlchemy itself.  Explicit rendering keeps
    autogenerated revisions self-contained and prevents migrations from
    depending on implementation-module names such as
    ``pgvector.sqlalchemy.vector.VECTOR``.
    """

    if (
        type_ == "type"
        and obj.__class__.__module__.startswith("pgvector")
    ):
        autogen_context.imports.add(
            "from pgvector.sqlalchemy import Vector"
        )

        dimension = getattr(obj, "dim", None)

        if dimension is None:
            return "Vector()"

        return f"Vector({int(dimension)})"

    # False means: let Alembic use its normal renderer.
    return False


# ---------------------------------------------------------------------------
# Migration configuration
# ---------------------------------------------------------------------------


def _configure_context(**kwargs: Any) -> None:
    """Apply project-wide Alembic comparison rules."""

    context.configure(
        target_metadata=target_metadata,
        compare_type=True,
        compare_server_default=True,
        include_schemas=False,
        render_item=_render_item,
        version_table="alembic_version",
        transaction_per_migration=True,
        **kwargs,
    )


# ---------------------------------------------------------------------------
# Offline mode
# ---------------------------------------------------------------------------


def run_migrations_offline() -> None:
    """Run migrations without opening a database connection."""

    _configure_context(
        url=settings.database_url,
        literal_binds=True,
        dialect_opts={
            "paramstyle": "named",
        },
    )

    with context.begin_transaction():
        context.run_migrations()


# ---------------------------------------------------------------------------
# Online mode
# ---------------------------------------------------------------------------


def run_migrations_online() -> None:
    """Run migrations against the configured PostgreSQL database."""

    connectable = create_engine(
        settings.database_url,
        poolclass=pool.NullPool,
        pool_pre_ping=True,
    )

    try:
        with connectable.connect() as connection:
            _configure_context(
                connection=connection,
            )

            with context.begin_transaction():
                context.run_migrations()
    finally:
        connectable.dispose()


if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
