"""baseline application schema

Revision ID: 105eefbcbdb6
Revises: 20260830_0000
Create Date: 2026-08-30 00:11:32.660270
"""

from __future__ import annotations

from typing import Sequence
from typing import Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql


revision: str = '105eefbcbdb6'
down_revision: Union[str, Sequence[str], None] = '20260830_0000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply this migration."""
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=2048), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts'))
    )
    op.create_index(op.f('ix_accounts_email'), 'accounts', ['email'], unique=True)
    op.create_index(op.f('ix_accounts_username'), 'accounts', ['username'], unique=True)
    op.create_table('face_profiles',
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_face_profiles'))
    )
    op.create_index(op.f('ix_face_profiles_label'), 'face_profiles', ['label'], unique=False)
    op.create_index(op.f('ix_face_profiles_status'), 'face_profiles', ['status'], unique=False)
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=150), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspaces'))
    )
    op.create_index(op.f('ix_workspaces_is_active'), 'workspaces', ['is_active'], unique=False)
    op.create_index(op.f('ix_workspaces_name'), 'workspaces', ['name'], unique=True)
    op.create_index(op.f('ix_workspaces_slug'), 'workspaces', ['slug'], unique=True)
    op.create_table('projects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_projects_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects'))
    )
    op.create_index(op.f('ix_projects_is_active'), 'projects', ['is_active'], unique=False)
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_index(op.f('ix_projects_workspace_id'), 'projects', ['workspace_id'], unique=False)
    op.create_table('workspace_memberships',
    sa.Column('workspace_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'ANALYST', 'VIEWER', name='workspace_role'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name=op.f('fk_workspace_memberships_account_id_accounts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], name=op.f('fk_workspace_memberships_workspace_id_workspaces'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workspace_memberships')),
    sa.UniqueConstraint('workspace_id', 'account_id', name='uq_workspace_membership')
    )
    op.create_index(op.f('ix_workspace_memberships_account_id'), 'workspace_memberships', ['account_id'], unique=False)
    op.create_index(op.f('ix_workspace_memberships_workspace_id'), 'workspace_memberships', ['workspace_id'], unique=False)
    op.create_table('cases',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_cases_project_id_projects'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases'))
    )
    op.create_index(op.f('ix_cases_project_id'), 'cases', ['project_id'], unique=False)
    op.create_table('ai_analyses',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('analysis_type', sa.Enum('SENTIMENT', 'RELATIONSHIP', 'ENTITY_EXTRACTION', 'SUMMARIZATION', 'CLASSIFICATION', 'OTHER', name='analysis_type'), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_ai_analyses_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_analyses'))
    )
    op.create_index(op.f('ix_ai_analyses_analysis_type'), 'ai_analyses', ['analysis_type'], unique=False)
    op.create_index(op.f('ix_ai_analyses_case_id'), 'ai_analyses', ['case_id'], unique=False)
    op.create_index('ix_ai_analysis_case_type', 'ai_analyses', ['case_id', 'analysis_type'], unique=False)
    op.create_table('artifacts',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('artifact_type', sa.Enum('GRAPH', 'TIMELINE', 'MAP', 'REPORT', 'IMAGE', 'VIDEO', 'EXPORT', 'ARCHIVE', 'OTHER', name='artifact_type'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_artifacts_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_artifacts'))
    )
    op.create_index(op.f('ix_artifacts_artifact_type'), 'artifacts', ['artifact_type'], unique=False)
    op.create_index(op.f('ix_artifacts_case_id'), 'artifacts', ['case_id'], unique=False)
    op.create_index('ix_artifacts_case_type', 'artifacts', ['case_id', 'artifact_type'], unique=False)
    op.create_table('entities',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Enum('PERSON', 'ORGANIZATION', 'LOCATION', 'ADDRESS', 'PHONE', 'EMAIL', 'USERNAME', 'DOMAIN', 'URL', 'IP', 'VEHICLE', 'DOCUMENT', 'ACCOUNT', 'OTHER', 'BANK_CARD', name='entity_type'), nullable=False),
    sa.Column('value', sa.String(length=512), nullable=False),
    sa.Column('normalized_value', sa.String(length=512), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_entities_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entities'))
    )
    op.create_index(op.f('ix_entities_case_id'), 'entities', ['case_id'], unique=False)
    op.create_index('ix_entities_case_type', 'entities', ['case_id', 'entity_type'], unique=False)
    op.create_index('ix_entities_case_value', 'entities', ['case_id', 'value'], unique=False)
    op.create_index(op.f('ix_entities_entity_type'), 'entities', ['entity_type'], unique=False)
    op.create_index(op.f('ix_entities_normalized_value'), 'entities', ['normalized_value'], unique=False)
    op.create_index(op.f('ix_entities_value'), 'entities', ['value'], unique=False)
    op.create_table('notes',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_notes_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notes'))
    )
    op.create_index(op.f('ix_notes_case_id'), 'notes', ['case_id'], unique=False)
    op.create_table('reports',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('report_type', sa.Enum('SUMMARY', 'AI_ANALYSIS', 'TIMELINE', 'RELATIONSHIP', 'EXPORT', 'OTHER', name='report_type'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_reports_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports'))
    )
    op.create_index(op.f('ix_reports_case_id'), 'reports', ['case_id'], unique=False)
    op.create_index('ix_reports_case_type', 'reports', ['case_id', 'report_type'], unique=False)
    op.create_index(op.f('ix_reports_report_type'), 'reports', ['report_type'], unique=False)
    op.create_table('search_indexes',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('object_type', sa.Enum('MESSAGE', 'DOCUMENT', 'EVIDENCE', 'ENTITY', 'ARTIFACT', 'REPORT', 'NOTE', name='search_object_type'), nullable=False),
    sa.Column('object_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_search_indexes_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_indexes'))
    )
    op.create_index(op.f('ix_search_indexes_case_id'), 'search_indexes', ['case_id'], unique=False)
    op.create_index('ix_search_indexes_case_type', 'search_indexes', ['case_id', 'object_type'], unique=False)
    op.create_index('ix_search_indexes_object', 'search_indexes', ['object_type', 'object_id'], unique=False)
    op.create_index(op.f('ix_search_indexes_object_id'), 'search_indexes', ['object_id'], unique=False)
    op.create_index(op.f('ix_search_indexes_object_type'), 'search_indexes', ['object_type'], unique=False)
    op.create_table('sources',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.Enum('TELEGRAM', 'WHATSAPP', 'SIGNAL', 'DISCORD', 'VK', 'FACEBOOK', 'INSTAGRAM', 'X', 'EMAIL', 'FILE', 'DIRECTORY', 'IMAGE', 'VIDEO', 'AUDIO', 'DOCUMENT', 'PDF', 'CSV', 'JSON', 'HTML', 'WEBSITE', 'DATABASE', 'API', 'OSINT', 'OTHER', name='source_type'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IMPORTING', 'READY', 'FAILED', 'IMPORTED', name='source_status'), nullable=False),
    sa.Column('original_path', sa.String(length=1024), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('imported_records', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_sources_case_id_cases'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources'))
    )
    op.create_index(op.f('ix_sources_case_id'), 'sources', ['case_id'], unique=False)
    op.create_index('ix_sources_case_type', 'sources', ['case_id', 'source_type'], unique=False)
    op.create_index(op.f('ix_sources_checksum'), 'sources', ['checksum'], unique=False)
    op.create_index(op.f('ix_sources_source_type'), 'sources', ['source_type'], unique=False)
    op.create_index(op.f('ix_sources_status'), 'sources', ['status'], unique=False)
    op.create_table('documents',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=True),
    sa.Column('document_type', sa.Enum('PDF', 'DOC', 'DOCX', 'TXT', 'HTML', 'CSV', 'JSON', 'REPORT', 'OTHER', name='document_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_documents_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_documents_source_id_sources'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_case_id'), 'documents', ['case_id'], unique=False)
    op.create_index('ix_documents_case_type', 'documents', ['case_id', 'document_type'], unique=False)
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_index(op.f('ix_documents_sha256'), 'documents', ['sha256'], unique=False)
    op.create_index(op.f('ix_documents_source_id'), 'documents', ['source_id'], unique=False)
    op.create_table('entity_merges',
    sa.Column('source_entity_id', sa.Uuid(), nullable=False),
    sa.Column('target_entity_id', sa.Uuid(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], name=op.f('fk_entity_merges_source_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], name=op.f('fk_entity_merges_target_entity_id_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_merges'))
    )
    op.create_index('ix_entity_merge_source_target', 'entity_merges', ['source_entity_id', 'target_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_merges_source_entity_id'), 'entity_merges', ['source_entity_id'], unique=False)
    op.create_index(op.f('ix_entity_merges_target_entity_id'), 'entity_merges', ['target_entity_id'], unique=False)
    op.create_table('evidences',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_type', sa.Enum('IMAGE', 'VIDEO', 'AUDIO', 'DOCUMENT', 'ARCHIVE', 'CONTACT', 'LOCATION', 'LINK', 'PHONE', 'EMAIL', 'USERNAME', 'HASH', 'METADATA', 'MESSAGE', 'OTHER', name='evidence_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('value', sa.String(length=1024), nullable=True),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('mime_type', sa.String(length=128), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_evidences_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_evidences_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidences'))
    )
    op.create_index(op.f('ix_evidences_case_id'), 'evidences', ['case_id'], unique=False)
    op.create_index('ix_evidences_case_type', 'evidences', ['case_id', 'evidence_type'], unique=False)
    op.create_index(op.f('ix_evidences_evidence_type'), 'evidences', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_evidences_sha256'), 'evidences', ['sha256'], unique=False)
    op.create_index(op.f('ix_evidences_source_id'), 'evidences', ['source_id'], unique=False)
    op.create_index('ix_evidences_source_type', 'evidences', ['source_id', 'evidence_type'], unique=False)
    op.create_table('relationships',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('source_entity_id', sa.Uuid(), nullable=False),
    sa.Column('target_entity_id', sa.Uuid(), nullable=False),
    sa.Column('relationship_type', sa.Enum('KNOWS', 'CONTACTED', 'CALLED', 'EMAILED', 'MESSAGED', 'MEMBER_OF', 'OWNS', 'LOCATED_AT', 'RELATED_TO', 'OTHER', name='relationship_type'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_relationships_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_entity_id'], ['entities.id'], name=op.f('fk_relationships_source_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_entity_id'], ['entities.id'], name=op.f('fk_relationships_target_entity_id_entities'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_relationships'))
    )
    op.create_index(op.f('ix_relationships_case_id'), 'relationships', ['case_id'], unique=False)
    op.create_index('ix_relationships_case_type', 'relationships', ['case_id', 'relationship_type'], unique=False)
    op.create_index(op.f('ix_relationships_relationship_type'), 'relationships', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_relationships_source_entity_id'), 'relationships', ['source_entity_id'], unique=False)
    op.create_index('ix_relationships_source_target', 'relationships', ['source_entity_id', 'target_entity_id'], unique=False)
    op.create_index(op.f('ix_relationships_target_entity_id'), 'relationships', ['target_entity_id'], unique=False)
    op.create_table('search_embeddings',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('search_index_id', sa.UUID(), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('embedding', Vector(768), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_search_embeddings_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['search_index_id'], ['search_indexes.id'], name=op.f('fk_search_embeddings_search_index_id_search_indexes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_embeddings')),
    sa.UniqueConstraint('search_index_id', 'model', name='uq_search_embedding_index_model')
    )
    op.create_index(op.f('ix_search_embeddings_case_id'), 'search_embeddings', ['case_id'], unique=False)
    op.create_index(op.f('ix_search_embeddings_model'), 'search_embeddings', ['model'], unique=False)
    op.create_index(op.f('ix_search_embeddings_object_id'), 'search_embeddings', ['object_id'], unique=False)
    op.create_index(op.f('ix_search_embeddings_object_type'), 'search_embeddings', ['object_type'], unique=False)
    op.create_index(op.f('ix_search_embeddings_search_index_id'), 'search_embeddings', ['search_index_id'], unique=False)
    op.create_table('search_semantic_chunks',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('chunk_key', sa.String(length=128), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('chat_name', sa.String(length=255), nullable=True),
    sa.Column('chunk_order', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('message_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_search_semantic_chunks_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_search_semantic_chunks_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_semantic_chunks')),
    sa.UniqueConstraint('case_id', 'chunk_key', name='uq_search_semantic_chunk_case_key')
    )
    op.create_index(op.f('ix_search_semantic_chunks_case_id'), 'search_semantic_chunks', ['case_id'], unique=False)
    op.create_index(op.f('ix_search_semantic_chunks_chat_name'), 'search_semantic_chunks', ['chat_name'], unique=False)
    op.create_index(op.f('ix_search_semantic_chunks_chunk_key'), 'search_semantic_chunks', ['chunk_key'], unique=False)
    op.create_index(op.f('ix_search_semantic_chunks_chunk_order'), 'search_semantic_chunks', ['chunk_order'], unique=False)
    op.create_index(op.f('ix_search_semantic_chunks_content_hash'), 'search_semantic_chunks', ['content_hash'], unique=False)
    op.create_index(op.f('ix_search_semantic_chunks_ended_at'), 'search_semantic_chunks', ['ended_at'], unique=False)
    op.create_index(op.f('ix_search_semantic_chunks_source_id'), 'search_semantic_chunks', ['source_id'], unique=False)
    op.create_index(op.f('ix_search_semantic_chunks_started_at'), 'search_semantic_chunks', ['started_at'], unique=False)
    op.create_table('timeline_events',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('event_type', sa.Enum('MESSAGE', 'DOCUMENT', 'FILE', 'CALL', 'EMAIL', 'RELATIONSHIP', 'ENTITY_CREATED', 'ENTITY_UPDATED', 'LOCATION', 'OTHER', name='timeline_event_type'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('event_time', sa.String(length=64), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_timeline_events_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_timeline_events_entity_id_entities'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timeline_events'))
    )
    op.create_index(op.f('ix_timeline_events_case_id'), 'timeline_events', ['case_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_entity_id'), 'timeline_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_event_time'), 'timeline_events', ['event_time'], unique=False)
    op.create_index(op.f('ix_timeline_events_event_type'), 'timeline_events', ['event_type'], unique=False)
    op.create_table('evidence_entities',
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], name=op.f('fk_evidence_entities_entity_id_entities'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.id'], name=op.f('fk_evidence_entities_evidence_id_evidences'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_entities'))
    )
    op.create_index(op.f('ix_evidence_entities_entity_id'), 'evidence_entities', ['entity_id'], unique=False)
    op.create_index(op.f('ix_evidence_entities_evidence_id'), 'evidence_entities', ['evidence_id'], unique=False)
    op.create_index('ix_evidence_entities_unique', 'evidence_entities', ['evidence_id', 'entity_id'], unique=False)
    op.create_table('face_embeddings',
    sa.Column('profile_id', sa.Uuid(), nullable=True),
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('face_id', sa.String(length=128), nullable=False),
    sa.Column('face_index', sa.Integer(), nullable=False),
    sa.Column('embedding', Vector(128), nullable=False),
    sa.Column('recognizer', sa.String(length=128), nullable=False),
    sa.Column('detector', sa.String(length=128), nullable=False),
    sa.Column('detection_confidence', sa.Float(), nullable=True),
    sa.Column('bbox_json', sa.Text(), nullable=True),
    sa.Column('source_metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_face_embeddings_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.id'], name=op.f('fk_face_embeddings_evidence_id_evidences'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['face_profiles.id'], name=op.f('fk_face_embeddings_profile_id_face_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_face_embeddings'))
    )
    op.create_index(op.f('ix_face_embeddings_case_id'), 'face_embeddings', ['case_id'], unique=False)
    op.create_index('ix_face_embeddings_evidence_face', 'face_embeddings', ['evidence_id', 'face_id'], unique=True)
    op.create_index(op.f('ix_face_embeddings_evidence_id'), 'face_embeddings', ['evidence_id'], unique=False)
    op.create_index('ix_face_embeddings_profile_case', 'face_embeddings', ['profile_id', 'case_id'], unique=False)
    op.create_index(op.f('ix_face_embeddings_profile_id'), 'face_embeddings', ['profile_id'], unique=False)
    op.create_table('messages',
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('evidence_id', sa.Uuid(), nullable=True),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('sender', sa.String(length=255), nullable=True),
    sa.Column('receiver', sa.String(length=255), nullable=True),
    sa.Column('chat_name', sa.String(length=255), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('reply_to_id', sa.Uuid(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_messages_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidences.id'], name=op.f('fk_messages_evidence_id_evidences'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reply_to_id'], ['messages.id'], name=op.f('fk_messages_reply_to_id_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_messages_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_index(op.f('ix_messages_case_id'), 'messages', ['case_id'], unique=False)
    op.create_index('ix_messages_case_sent_at', 'messages', ['case_id', 'sent_at'], unique=False)
    op.create_index(op.f('ix_messages_chat_name'), 'messages', ['chat_name'], unique=False)
    op.create_index(op.f('ix_messages_evidence_id'), 'messages', ['evidence_id'], unique=False)
    op.create_index(op.f('ix_messages_external_id'), 'messages', ['external_id'], unique=False)
    op.create_index(op.f('ix_messages_receiver'), 'messages', ['receiver'], unique=False)
    op.create_index(op.f('ix_messages_sender'), 'messages', ['sender'], unique=False)
    op.create_index('ix_messages_sender_chat', 'messages', ['sender', 'chat_name'], unique=False)
    op.create_index(op.f('ix_messages_sent_at'), 'messages', ['sent_at'], unique=False)
    op.create_index(op.f('ix_messages_source_id'), 'messages', ['source_id'], unique=False)
    op.create_index('ix_messages_source_sent_at', 'messages', ['source_id', 'sent_at'], unique=False)
    op.create_table('search_semantic_chunk_embeddings',
    sa.Column('case_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('embedding', Vector(768), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_search_semantic_chunk_embeddings_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['chunk_id'], ['search_semantic_chunks.id'], name=op.f('fk_search_semantic_chunk_embeddings_chunk_id_search_semantic_chunks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_search_semantic_chunk_embeddings')),
    sa.UniqueConstraint('chunk_id', 'model', name='uq_search_semantic_chunk_embedding_chunk_model')
    )
    op.create_index(op.f('ix_search_semantic_chunk_embeddings_case_id'), 'search_semantic_chunk_embeddings', ['case_id'], unique=False)
    op.create_index(op.f('ix_search_semantic_chunk_embeddings_chunk_id'), 'search_semantic_chunk_embeddings', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_search_semantic_chunk_embeddings_content_hash'), 'search_semantic_chunk_embeddings', ['content_hash'], unique=False)
    op.create_index(op.f('ix_search_semantic_chunk_embeddings_model'), 'search_semantic_chunk_embeddings', ['model'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_search_semantic_chunk_embeddings_model'), table_name='search_semantic_chunk_embeddings')
    op.drop_index(op.f('ix_search_semantic_chunk_embeddings_content_hash'), table_name='search_semantic_chunk_embeddings')
    op.drop_index(op.f('ix_search_semantic_chunk_embeddings_chunk_id'), table_name='search_semantic_chunk_embeddings')
    op.drop_index(op.f('ix_search_semantic_chunk_embeddings_case_id'), table_name='search_semantic_chunk_embeddings')
    op.drop_table('search_semantic_chunk_embeddings')
    op.drop_index('ix_messages_source_sent_at', table_name='messages')
    op.drop_index(op.f('ix_messages_source_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_sent_at'), table_name='messages')
    op.drop_index('ix_messages_sender_chat', table_name='messages')
    op.drop_index(op.f('ix_messages_sender'), table_name='messages')
    op.drop_index(op.f('ix_messages_receiver'), table_name='messages')
    op.drop_index(op.f('ix_messages_external_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_evidence_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_chat_name'), table_name='messages')
    op.drop_index('ix_messages_case_sent_at', table_name='messages')
    op.drop_index(op.f('ix_messages_case_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_face_embeddings_profile_id'), table_name='face_embeddings')
    op.drop_index('ix_face_embeddings_profile_case', table_name='face_embeddings')
    op.drop_index(op.f('ix_face_embeddings_evidence_id'), table_name='face_embeddings')
    op.drop_index('ix_face_embeddings_evidence_face', table_name='face_embeddings')
    op.drop_index(op.f('ix_face_embeddings_case_id'), table_name='face_embeddings')
    op.drop_table('face_embeddings')
    op.drop_index('ix_evidence_entities_unique', table_name='evidence_entities')
    op.drop_index(op.f('ix_evidence_entities_evidence_id'), table_name='evidence_entities')
    op.drop_index(op.f('ix_evidence_entities_entity_id'), table_name='evidence_entities')
    op.drop_table('evidence_entities')
    op.drop_index(op.f('ix_timeline_events_event_type'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_event_time'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_entity_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_case_id'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_search_semantic_chunks_started_at'), table_name='search_semantic_chunks')
    op.drop_index(op.f('ix_search_semantic_chunks_source_id'), table_name='search_semantic_chunks')
    op.drop_index(op.f('ix_search_semantic_chunks_ended_at'), table_name='search_semantic_chunks')
    op.drop_index(op.f('ix_search_semantic_chunks_content_hash'), table_name='search_semantic_chunks')
    op.drop_index(op.f('ix_search_semantic_chunks_chunk_order'), table_name='search_semantic_chunks')
    op.drop_index(op.f('ix_search_semantic_chunks_chunk_key'), table_name='search_semantic_chunks')
    op.drop_index(op.f('ix_search_semantic_chunks_chat_name'), table_name='search_semantic_chunks')
    op.drop_index(op.f('ix_search_semantic_chunks_case_id'), table_name='search_semantic_chunks')
    op.drop_table('search_semantic_chunks')
    op.drop_index(op.f('ix_search_embeddings_search_index_id'), table_name='search_embeddings')
    op.drop_index(op.f('ix_search_embeddings_object_type'), table_name='search_embeddings')
    op.drop_index(op.f('ix_search_embeddings_object_id'), table_name='search_embeddings')
    op.drop_index(op.f('ix_search_embeddings_model'), table_name='search_embeddings')
    op.drop_index(op.f('ix_search_embeddings_case_id'), table_name='search_embeddings')
    op.drop_table('search_embeddings')
    op.drop_index(op.f('ix_relationships_target_entity_id'), table_name='relationships')
    op.drop_index('ix_relationships_source_target', table_name='relationships')
    op.drop_index(op.f('ix_relationships_source_entity_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_relationship_type'), table_name='relationships')
    op.drop_index('ix_relationships_case_type', table_name='relationships')
    op.drop_index(op.f('ix_relationships_case_id'), table_name='relationships')
    op.drop_table('relationships')
    op.drop_index('ix_evidences_source_type', table_name='evidences')
    op.drop_index(op.f('ix_evidences_source_id'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_sha256'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_evidence_type'), table_name='evidences')
    op.drop_index('ix_evidences_case_type', table_name='evidences')
    op.drop_index(op.f('ix_evidences_case_id'), table_name='evidences')
    op.drop_table('evidences')
    op.drop_index(op.f('ix_entity_merges_target_entity_id'), table_name='entity_merges')
    op.drop_index(op.f('ix_entity_merges_source_entity_id'), table_name='entity_merges')
    op.drop_index('ix_entity_merge_source_target', table_name='entity_merges')
    op.drop_table('entity_merges')
    op.drop_index(op.f('ix_documents_source_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_sha256'), table_name='documents')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_index('ix_documents_case_type', table_name='documents')
    op.drop_index(op.f('ix_documents_case_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_sources_status'), table_name='sources')
    op.drop_index(op.f('ix_sources_source_type'), table_name='sources')
    op.drop_index(op.f('ix_sources_checksum'), table_name='sources')
    op.drop_index('ix_sources_case_type', table_name='sources')
    op.drop_index(op.f('ix_sources_case_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_search_indexes_object_type'), table_name='search_indexes')
    op.drop_index(op.f('ix_search_indexes_object_id'), table_name='search_indexes')
    op.drop_index('ix_search_indexes_object', table_name='search_indexes')
    op.drop_index('ix_search_indexes_case_type', table_name='search_indexes')
    op.drop_index(op.f('ix_search_indexes_case_id'), table_name='search_indexes')
    op.drop_table('search_indexes')
    op.drop_index(op.f('ix_reports_report_type'), table_name='reports')
    op.drop_index('ix_reports_case_type', table_name='reports')
    op.drop_index(op.f('ix_reports_case_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_notes_case_id'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_entities_value'), table_name='entities')
    op.drop_index(op.f('ix_entities_normalized_value'), table_name='entities')
    op.drop_index(op.f('ix_entities_entity_type'), table_name='entities')
    op.drop_index('ix_entities_case_value', table_name='entities')
    op.drop_index('ix_entities_case_type', table_name='entities')
    op.drop_index(op.f('ix_entities_case_id'), table_name='entities')
    op.drop_table('entities')
    op.drop_index('ix_artifacts_case_type', table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_case_id'), table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_artifact_type'), table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index('ix_ai_analysis_case_type', table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_case_id'), table_name='ai_analyses')
    op.drop_index(op.f('ix_ai_analyses_analysis_type'), table_name='ai_analyses')
    op.drop_table('ai_analyses')
    op.drop_index(op.f('ix_cases_project_id'), table_name='cases')
    op.drop_table('cases')
    op.drop_index(op.f('ix_workspace_memberships_workspace_id'), table_name='workspace_memberships')
    op.drop_index(op.f('ix_workspace_memberships_account_id'), table_name='workspace_memberships')
    op.drop_table('workspace_memberships')
    op.drop_index(op.f('ix_projects_workspace_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_active'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_workspaces_slug'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_name'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_is_active'), table_name='workspaces')
    op.drop_table('workspaces')
    op.drop_index(op.f('ix_face_profiles_status'), table_name='face_profiles')
    op.drop_index(op.f('ix_face_profiles_label'), table_name='face_profiles')
    op.drop_table('face_profiles')
    op.drop_index(op.f('ix_accounts_username'), table_name='accounts')
    op.drop_index(op.f('ix_accounts_email'), table_name='accounts')
    op.drop_table('accounts')

    # PostgreSQL named ENUM types are schema objects independent from tables.
    # Alembic's generated drop_table() calls do not reliably remove them.
    # Drop them explicitly so that:
    #
    #     alembic downgrade base
    #     alembic upgrade head
    #
    # is repeatable on PostgreSQL.
    enum_type_names = (
        "workspace_role",
        "analysis_type",
        "artifact_type",
        "entity_type",
        "report_type",
        "search_object_type",
        "source_type",
        "source_status",
        "document_type",
        "evidence_type",
        "relationship_type",
        "timeline_event_type",
    )

    for enum_type_name in enum_type_names:
        op.execute(
            sa.text(
                f'DROP TYPE IF EXISTS "{enum_type_name}"'
            )
        )

    # ### end Alembic commands ###
